<a href="https://colab.research.google.com/github/Shahidkp64/learnpi/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.71712974 0.28113881 0.30662286]
  [0.58492049 0.56782161 0.90999073]
  [0.68670229 0.38051435 0.01794212]]

 [[0.01653423 0.14228631 0.6373135 ]
  [0.15652723 0.66512274 0.862375  ]
  [0.24022603 0.93917791 0.21544215]]

 [[0.99055323 0.56123169 0.9488953 ]
  [0.96516292 0.95043685 0.78395933]
  [0.24744    0.12073823 0.44965213]]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [6]:
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]
