<a href="https://colab.research.google.com/github/Shahidkp64/learnpi/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [5]:
#please provide your answer below this line
import numpy as np
x =  a = np.arange(1, 17).reshape(4,4)

print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [12]:


 
import sys
 

def floorAndCeil(arr, n, x):
 
    # Distances of current
    # floor and ceiling
    fDist = sys.maxsize
    cDist = sys.maxsize
 
    for i in range(n):
     
        # If current element is closer
        # than previous ceiling.
        if (arr[i] >= x and
            cDist > (arr[i] - x)):
         
            cInd = i
            cDist = arr[i] - x
 
        # If current element is closer
        # than previous floor.
        if (arr[i] <= x and fDist > (x - arr[i])):
         
            fInd = i
            fDist = x - arr[i]
 
    if (fDist == sys.maxsize):
        print("Floor doesn't exist ")
    else:
        print("Floor is " + str(arr[fInd]))
 
    if (cDist == sys.maxsize):
        print( "Ceil doesn't exist ")
    else:
        print("Ceil is " + str(arr[cInd]))
 
# Driver code
if __name__ == "__main__":
    arr = [5, 6, 8, 9, 6, 5, 5, 6]
    n = len(arr)
    x = 7
    floorAndCeil(arr, n, x)

Floor is 6
Ceil is 8


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [14]:
#please provide your answer below this line.
#Python program explaining
# numpy.squeeze function
  
import numpy as geek
  
in_arr = geek.array([[[2, 2, 2], [2, 2, 2]]])
   
print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape)  
  
out_arr = geek.squeeze(in_arr) 
  
print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape) 

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)
